### PR TITLE
Support connecting express router in app config.

### PR DESCRIPTION
**Pull request by sarahssharkey**
Currently only an `Express` application can be connected with `createConfig`, however applications may use express `IRouter`s instead, e.g. for configuring routes on separate subdomains.

This change updates the expected type from `Express` to `IRouter` (which `Express` inherits from)

### CODE REVIEW

**Comment by RobinTail** [comment]
Interesting idea, @sarahssharkey .
Could you share an example application instance that complies `IRouter` interface, but not the `express()`?

**Comment by RobinTail** [comment]
Sorry, @sarahssharkey ,
did you mean that your PR enables to connect `express.Router()` ?
https://expressjs.com/en/4x/api.html#router

**Comment by sarahssharkey** [comment]
@RobinTail yes! so an example where someone would use express routers for subdomains would be
```
import express from 'express';
import subdomain from 'express-subdomain';
import {attachRouting, createConfig} from 'express-zod-api';

// overall express app
const app = express();

// routes for API subdomain
const apiRouter = express.Router();
const apiConfig = createConfig({app: apiRouter, cors: true, logger});
const apiRoutes = {
  ....
};
(async () => {
    await attachRouting(apiConfig, apiRoutes);
})();

// routes for dashboard subdomain
const dashboardRouter = express.Router();
const dashboardConfig = createConfig({app: dashboardRouter, cors: true, logger});
const dashboardRoutes = {
  ....
};
(async () => {
    await attachRouting(dashboardConfig, dashboardRoutes);
})();


// Attach routers to overall application under different subdomains
app.use(subdomain('api', apiRouter))
app.use(subdomain('dashboard', apiRouter))
```

I've done this for my own application and it works like a charm :)

**Review by RobinTail — APPROVED** [review]

**Comment by RobinTail** [comment]
Released within 15.3.0, @sarahssharkey 
Thank you

**Comment by sarahssharkey** [comment]
Thank you! And thanks for the quick response :)

**Pull request merged**
