### PR TITLE
Add operationId to Endpoint

### PR DESCRIPTION
**Pull request by lazylace37**
Expose operationId to the OperationObject

### CODE REVIEW

**Comment by RobinTail** [comment]
@lazylace37 , 
this approach would not work well, because `operationId` has to be unique, but you're making them set on the `Endpoint` level, which can handle several `methods`.

Would you mind if I'll make the `operationId` automatically generated from the Routing path and method?

**Comment by lazylace37** [comment]
Hi @RobinTail, you are correct and no, I wouldn't mind.
Thanks

**Comment by RobinTail** [comment]
The alternative solution is in #845

**Comment by RobinTail** [comment]
The feature released in version 8.10.0 and 9.0.0-beta3, @lazylace37

**Pull request closed without merging**
